service: shortedapp-normalize

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: ap-southeast-2

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
##DATA FETCHING/NORMALISE
  datanormalise:
    handler: datanormalise
    name: datanormalise
    description: Normalises the data from ASIC/ASX/etc.
    memorySize: 128
    timeout: 10 
    events:
      - schedule: rate(12 hours)
  bulknormalise:
    handler: bulknormalise
    name: bulknormalise
    description: Bulk normalises and ingest data into s3
    memorySize: 128
    timeout: 300 
    events:
      - sns: bulkingest
  datafetch:
    handler: datafetch
    name: datafetch
    description: Refresh long term data such as stock codes
    memorySize: 128
    timeout: 10 
     - schedule: rate(30 days)

##INGESTION
  dynamoingestor:
    handler: dynamoingestor
    name: dynamoingestor
    description: Ingest latest short data into dynamodb by code
    memorySize: 256
    timeout: 300 
    event:
      events:
      - sns: shorts
  topmoversingest:
    handler: topmoversingest
    name: topmoversingest
    description: Ingest movement statistics for eash stock
    memorySize: 256
    timeout: 300 
    events:
      - sns: shorts
  topshortsingestor:
    handler: topshortsingestor
    name: topshortsingestor
    description: Ingest the top shorts for the day based on order
    memorySize: 256
    timeout: 300 
    events:
      - sns: shorts

## QUERIES
  codedmoversquery:
    handler: codedmoversquery
    name: codedmoversquery
    description: Query the movement statistics for a particular stock code
    memorySize: 128
    timeout: 10 
    events:
      - http:
          path: codedmovers
          method: get
          cors: true
          querystrings:
            code: true
  topshortsquery:
    handler: topshortsquery
    name: topshortsquery
    description: Query the top X shorts for the day based on order
    memorySize: 256
    timeout: 300 
    events:
      - http:
          path: topshorts
          method: get
          cors: true
          querystrings:
            number: true
  topmoversquery:
    handler: topmoversquery
    name: topmoversquery
    description: Query the movement statistics for the top X stocks
    memorySize: 128
    timeout: 10 
    events:
      - http:
          path: topmovers
          method: get
          cors: true
          querystrings:
            number: true
  topshortseries:
    handler: topshortseries
    name: topshortseries
    description: Query to retreive the time series data for the top X stocks
    memorySize: 128
    timeout: 10 
    events:
      - http:
          path: topmovers
          method: get
          cors: true
          querystrings:
            number: true
#RESOURCES TO BE GENERATED BY CLOUDFORMATION
resources:
  Resources:
    lastUpdate:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lastUpdate
        AttributeDefinitions:
          - AttributeName: name_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: name_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    shorts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shorts
        #TODO add GSI
        AttributeDefinitions:
          #TODO ADD MORE HERE
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
        - IndexName: Code-Percent-index
          KeySchema:
            - AttributeName: code
              KeyType: HASH
            - AttributeName: percent
              KeyType: RANGE
          #TODO ADD ATTRIBUTES AND PROJECTION
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5